# Generated by Django 3.2.12 on 2022-02-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220208_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
