# Generated by Django 3.2.12 on 2022-02-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='text',
        ),
        migrations.AlterField(
            model_name='ask',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='time',
            field=models.IntegerField(),
        ),
    ]
