# Generated by Django 3.2.12 on 2022-02-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20220201_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
