from django.urls import path

from chat import views, api


app_name = "chat"

urlpatterns = [
    path(
        "index/",
        views.index,
        name="index"
    ),
    path(
        "archive/<int:offset>/",
        views.archive,
        name="archive"
    ),
    path(
        "accounts/login/",
        views.login_staff,
        name="login"
    ),
    path(
        "accounts/logout/",
        views.logout_staff,
        name="logout"
    ),
    path(
        "accounts/registration/",
        views.registration_staff,
        name="registration"
    ),
    path(
        "accounts/change/<int:pk>/",
        views.change_staff,
        name="change_staff"
    ),
    path(
        "accounts/staff_list/",
        views.staff_list,
        name="staff_list"
    ),
    path(
        "api/v1/note/",
        api.get_note,
        name="note"
    ),
    path(
        "api/v1/new_chat/<int:ucid>/",
        api.get_chat,
        name="new_chat"
    ),
    path(
        "api/v1/archive_chat/<int:ucid>/",
        api.archive_chat,
        name="archive_chat"
    ),
    path(
        "api/v1/unarchive_chat/<int:ucid>/",
        api.unarchive_chat,
        name="unarchive_chat"
    ),
    path(
        "api/v1/chats/",
        api.get_chats,
        name="chats"
    ),
    path(
        "api/v1/archived_chats/<int:offset>/",
        api.get_archived_chats,
        name="archived_chats"
    ),
    path(
        "api/v1/messages/<int:ucid>/",
        api.get_messages,
        name="messages"
    ),
    path(
        "api/v1/emoji/",
        api.get_emojis,
        name="emoji"
    ),
    path(
        "api/v1/upload_file/",
        api.upload_file,
        name="upload_file"
    ),
    path(
        "api/v1/delete_message/<int:message_id>/",
        api.delete_message,
        name="delete_message"
    ),
]
